rvm:
    - "2.0.0"
    - "1.9.3"
    - "1.9.2"
    - "1.8.7"
    - "jruby-1.7.4"
env:
    - OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=3.0.20
    - OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=3.1.12
    - OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=3.2.14
    - OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=4.0.0
    # - OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=master
matrix:
    exclude:
        -   rvm: 1.8.7
            env: OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=4.0.0
        -   rvm: 1.9.2
            env: OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=4.0.0
        -   rvm: 1.8.7
            env: OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=master
        -   rvm: 1.9.2
            env: OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=master
    allow_failures:
        -   rvm: 1.9.3
            env: OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=master
        -   rvm: 2.0.0
            env: OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=master
        -   rvm: jruby-1.7.4
            env: OBJECTIFIED_ENVIRONMENTS_RAILS_TEST_VERSION=master
